version: '2'

services:
  db:
    image: postgres:11-alpine
    volumes:
    - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - TZ=Asia/Tokyo
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test

