// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/purini-to/go-postgresql-restapi-sample/app"
	"github.com/purini-to/go-postgresql-restapi-sample/core/config"
	"github.com/purini-to/go-postgresql-restapi-sample/core/logger"
	"github.com/purini-to/go-postgresql-restapi-sample/router"
	"github.com/purini-to/go-postgresql-restapi-sample/server"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, func(), error) {
	mux := server.ProvideEngine()
	zapLogger, err := logger.ProvideLogger()
	if err != nil {
		return nil, nil, err
	}
	routerRouter := router.ProvideRouter(zapLogger)
	viper, err := config.ProvideConfig(zapLogger)
	if err != nil {
		return nil, nil, err
	}
	serverServer := server.ProvideServer(mux, routerRouter, viper)
	appApp := app.ProvideApp(serverServer)
	return appApp, func() {
	}, nil
}
