// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/purini-to/go-postgresql-restapi-sample/core/config"
	"github.com/purini-to/go-postgresql-restapi-sample/core/logger"
	"github.com/purini-to/go-postgresql-restapi-sample/interfaces/middleware"
	"github.com/purini-to/go-postgresql-restapi-sample/interfaces/router"
	"github.com/purini-to/go-postgresql-restapi-sample/interfaces/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, func(), error) {
	mux := server.NewEngine()
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	middlewareLogger := middleware.NewLogger(loggerLogger)
	recoverer := middleware.NewRecoverer(loggerLogger)
	routerRouter := router.NewRouter(loggerLogger, middlewareLogger, recoverer)
	serverServer := server.NewServer(mux, routerRouter, configConfig)
	return serverServer, func() {
	}, nil
}
