// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	app := ProvideApp()
	return app, func() {
	}, nil
}
